[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_ldf_mode = deep+
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps =
  bblanchon/ArduinoJson@^6.21.4
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
  adafruit/Adafruit Fingerprint Sensor Library@^2.1.3
  adafruit/RTClib@^2.1.4

[env:esp32-s3-devkitm-1]
board = esp32-s3-devkitm-1
build_flags =
  ${env.build_flags}
  -D CORE_DEBUG_LEVEL=0
  -D CAMPUS_USE_RTC=1
  -D CAMPUS_USE_SD=1

[env:esp32dev]
board = esp32dev
upload_port = COM3
upload_speed = 115200
monitor_port = COM3 
board_build.partitions = huge_app.csv
build_flags =
  ${env.build_flags}
  -D CORE_DEBUG_LEVEL=0
  -D CAMPUS_USE_RTC=1
  -D CAMPUS_USE_SD=1
